### ISSUE TITLE
Question: Package linking in example

### ISSUE THREAD

**Issue by JiriHoffmann** [ammarahm-ed/react-native-jsi-template#11]
Hi,

I was just wondering if there was a specific reason why you chose to import the package in the example like this:

https://github.com/ammarahm-ed/react-native-jsi-template/blob/1a923388bcbf0e9672c2f97dc133904dd1fda861/example/package.json#L15

Instead of keeping it how it's originally set up by npx create-react-native-library. Meaning it's imported in the `Podfile` for iOS and in `settings.gradle`, `build.gradle`, and `MainApplication.java` on Android. 

From my understanding, imports via package.json (the way you have it now) will create a copy of the template inside node_modules which means that changes made to the template will not be reflected unless it is reinstalled with `npm` or `yarn`. 

I understand that the import in package.json looks much cleaner, but it significantly slows down the workflow so for development purposes wouldn't it make sense to keep the setup by npx create-react-native-library? Unless there is some obvious reason that I am missing.

**Comment by ammarahm-ed** [comment]
@JiriHoffmann I agree, it becomes painful but at the time of writing, i was unable to get the example app to work with symlinked local package as you know react native does not support symlinking local packages and with JSI it becomes a bit more complicated.

However recently I have been able to symlink my own library so I will update those changes here soon. Thanks for bringing this to my attention.

**Comment by ammarahm-ed** [comment]
@JiriHoffmann A PR would be really helpful.
